### ISSUE TITLE
Missing util folder

### ISSUE THREAD

**Issue by SaraAlthubaiti** [yangdongchao/LLM-Codec#4]
Hi LLM-Codec authors,

First of all, thank you for such great work; I'm excited to try it! :)

While I'm trying to run `infer_code/eval_accent_understanding_v2.py`, it shows that:

`Traceback (most recent call last):
  File "infer_code/eval_accent_understanding_v2.py", line 32, in <module>
    from util.misc import NativeScalerWithGradNormCount as NativeScaler
ModuleNotFoundError: No module named 'util'`

Which tell that there is a missing `util` folder.

Could you please update the repository with this folder?

**Comment by yangdongchao** [comment]
> Hi LLM-Codec authors,
> 
> First of all, thank you for such great work; I'm excited to try it! :)
> 
> While I'm trying to run `infer_code/eval_accent_understanding_v2.py`, it shows that:
> 
> `Traceback (most recent call last): File "infer_code/eval_accent_understanding_v2.py", line 32, in <module> from util.misc import NativeScalerWithGradNormCount as NativeScaler ModuleNotFoundError: No module named 'util'`
> 
> Which tell that there is a missing `util` folder.
> 
> Could you please update the repository with this folder?

I have update it.
